# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17656c52b6f1ef5348f79e20e31d9c4430ab4000fedf603d5e9d3878f2b22e9b4a9e0ad9909a1a0da5736002d391a02edf37552f8c34cc29dfb466633bd451b8

test:
  secret_key_base: 6bbd2343495209b8a3db0aa4fc68338621b06fc8010f355a050fc5cc1e571ed1dceeae9896049846a1ef65b8139a5cdd9db0a70e8779a683dff331c23e1474a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
